name: video_slider
description: A simple slider of video to trim by specific area.
version: 0.0.2
homepage: https://github.com/YuheiNakasaka/flutter_video_slider

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter_min_gpl: ^5.1.0
  video_player: ^2.6.1
  video_thumbnail: ^0.5.3
  path_provider: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic:
  pedantic_mono:

flutter:
